name: SReC
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit-dev=10.1.243=h516909a_3
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.21.5=py37h1e6e340_3
  - openssl=3.4.0=h7b32b05_1
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.12=hf930737_100_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - awscli==1.31.13
      - botocore==1.33.13
      - cachetools==5.5.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.4
      - cycler==0.11.0
      - debugpy==1.4.0
      - docutils==0.16
      - flatbuffers==25.2.10
      - future==1.0.0
      - gast==0.4.0
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - h5py==3.8.0
      - idna==3.10
      - imageio==2.9.0
      - importlib-metadata==6.7.0
      - jmespath==1.0.1
      - joblib==1.3.2
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.2.2
      - networkx==2.6.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.3.5
      - pillow==5.3.0
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-version==0.0.2
      - pytz==2025.1
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.7.2
      - s3transfer==0.8.2
      - scikit-image==0.18.3
      - scikit-learn==1.0.2
      - scipy==1.1.0
      - seaborn==0.12.2
      - six==1.17.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - torch==1.1.0
      - torchac-backend-gpu==1.0.0
      - torchvision==0.2.1
      - typing-extensions==4.7.1
      - urllib3==1.26.20
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - zipp==3.15.0
prefix: /mnt/ssd-data/vaidya/anaconda/envs/SReC
